### ISSUE TITLE
Misc questions

### ISSUE THREAD

**Issue by vicb** [timostamm/protobuf-ts#11]
First of all thanks for this great lib !

I have a few questions about the runtime:

The lib uses custom [base64 functions](https://github.com/timostamm/protobuf-ts/blob/master/packages/runtime/src/base64.ts). Have you considered using the platform instead ? (`Buffer` on node and `atob` and `btoa` in the browser). I understand that the current decode might be more lenient but I'm not sure if this is really needed and if it is it should not be to hard to implement.

Have you considered using `const enums` in the runtime ? i.e. for [`ScalarType`](https://github.com/timostamm/protobuf-ts/blob/7a219638b830d93b79ac30917f5c60e4db89b866/packages/runtime/src/reflection-info.ts#L291). This could also save some bytes - it would technically be a breaking change if someone uses the enum in their code.

I am happy to submit PRs for those if it can help.

Thanks

**Comment by timostamm** [comment]
Hey @vicb, 

**const enums**

Earlier versions did use `const enum`, but this caused problems:

`const enum` in a module breaks the react build process. React enforces the TypeScript compiler option `isolatedModules`, which does not allow `const enum`. It is likely that there are other situations where a user needs `isolatedModules`.

Therefore, `const enum` was dropped in #4. This increased the [webpack build size by ~4%](https://github.com/timostamm/protobuf-ts/pull/4/commits/45cf668a690438d0a8104b6c2d8a5d27070f9d83#diff-201a2f185bb0bd20fc824a4903c2069ce0e65809bed814e5bffb3c49fb2ff888R1119). But code size is still a fraction of all other protobuf libs I know. 


**base64** 

The functions compile to about 1.6kb minified JS. I think it should be possible to drop 1kb by using platform features. That would be a small but considerable improvement.

The functions are used by the JSON format ([reflection-json-reader.ts](https://github.com/timostamm/protobuf-ts/blob/7a219638b830d93b79ac30917f5c60e4db89b866/packages/runtime/src/reflection-json-reader.ts), [reflection-json-writer.ts](https://github.com/timostamm/protobuf-ts/blob/7a219638b830d93b79ac30917f5c60e4db89b866/packages/runtime/src/reflection-json-writer.ts)) and [grpc-web-format.ts](https://github.com/timostamm/protobuf-ts/blob/7a219638b830d93b79ac30917f5c60e4db89b866/packages/grpcweb-transport/src/grpc-web-format.ts).

The leniency in decoding has two reasons:
1. compatibility with the protobuf JSON format
   
   Compatibility is currently tested with the protobuf conformance test suite. The test suite only runs against nodejs. When we introduce platform specific code, some more test coverage for base64 is necessary. Unit tests can be added to the runtime, which is tested against both nodejs and browser. 

2. allow inner padding for [easy reading of chunked grpc-web response](https://github.com/timostamm/protobuf-ts/blob/7a219638b830d93b79ac30917f5c60e4db89b866/packages/grpcweb-transport/src/grpc-web-format.ts#L154)
   
   I think it is fine to rewrite the grpc-web function and drop support for inner padding.

A PR would be welcome!

**Comment by vicb** [comment]
Thanks for you quick and detailed answer.

Good to know about const enum breaking react.

> But code size is still a fraction of all other protobuf libs I know.

I used mapbox/pbf before which generates really tiny files - but no typescript and not maintained either.

I'll send a PR for the base64 functions in the coming days.

**Comment by vicb** [comment]
Regarding base64, `atob()` and `btoa()` only support unicode string but not arbitrary binary data.

It means that it would not be possible to use them in the browser where the space saving would be most required :( 

It's a shame but I have to close this issue. Sorry.

**Comment by timostamm** [comment]
No worries, @vicb 

If you have any other suggestions, please let me know. 

BTW, thanks for pointing out mapbox/pbf!  Added it to the code size benchmarks: 

| generator               | version         | optimize for      | webpack output size |
|-------------------------|----------------:|-------------------|--------------------:|
| pbf | 3.2.1 |  | 22,132 b |
| protobuf-ts | 1.0.5 | size | 42,353 b |
| protobuf-ts | 1.0.5 | speed | 72,855 b |
| ts-proto | 1.26.0 |  | 111,825 b |
| google-protobuf | 3.12.2 |  | 396,934 b |

Looks like we have a new target to beat :)

**Comment by vicb** [comment]
@timostamm before finding your great plugin I thought about creating mine so I have some ideas on what I would like, maybe I can share some of it if you are interested. I could also help implementing some of those if you are interested.

- Use JS `Map` instead of objects for maps - whatever way should be documented,
- Being able to control what is generated, i.e. drop JSON for people who are not using it. Merge and is could also be candidate,
- Use [ts-morph](https://ts-morph.com/) instead of tapping directly in the TS API. Probably to be considered only if the code generation should be changed (i.e. to implement the previous bullet point)

It would be nice to add an eslint config to the project to automate code formatting and ease contributions.

**Comment by timostamm** [comment]
**JS Map:** 

The problem with Map is accessing the items. `Map.keys()`, `entries()` and `values()` return `IterableIterator`.  Using `IterableIterator` in `for` loops requires the TypeScript compiler option `downlevelIteration, which is still disabled by default. See [stackoverflow](https://stackoverflow.com/questions/53441292/why-downleveliteration-is-not-on-by-default).


**Control what is generated:** 

Yes, it would be very beneficial if unused features would be excluded in production builds. 
But I am not convinced that plugin options are the way to go. I think the generated code should be as stable as possible. A plugin option should not break userland code if possible. 

There is an alternative I have been thinking about. If there was a function `toJson(msg)` instead of `MyMessage.toJson(msg: MyMessage)`, tree shakers would strip the function from production builds if it is not used. If you are interested I can commit this in an experimental branch.


**tslint:**

Absolutely agree. 


**ts-morph:** 

The compiler API is painfully verbose. [ts-ast-viewer.com](https://ts-ast-viewer.com/#code/GYVwdgxgLglg9mABMOcAUBKRBvAUIgxAJwFMoQikAiAIwEMiqBuXAXyA) helps a lot... Have no experience with ts-morph. Might be worth it.


**Other ideas:**
- Make it easier to work with reflection. Goal: easily generate a form for a protobuf message (including validation with custom options, for example max-length, etc.). 
- Documentation: better readability, switch to docusaurus?

**Comment by vicb** [comment]
**Map**

The easy solution is to use `Array.from(...)`. 
Slightly less easy but more memory efficient is to call `next()`.

**What is generated**

Agreed that compiler options might not be ideal... but it's typescript, you would now right away if you miss a method and stripping code would be opt-in. I think mapbox/pbf also allow to generate read or write only methods.

But if there is a way without compiler options it might be better.

**Other topics**

What about creating issues for all know item to work on ?
Could be one issue per identified item + one "misc issues" with smaller/exploratory ideas.
