### ISSUE TITLE
What's the difference between "text" and "binary" format?

### ISSUE THREAD

**Issue by frederikhors** [timostamm/protobuf-ts#117]
I'm using https://github.com/improbable-eng/grpc-web/tree/master/go/grpcweb as backend.

In MANUAL I can read:

> format: "text" | "binary"

> Send binary or text format? Defaults to text.

`improbable-eng/grpc-web` works with both but I don't understand what's the difference between the two formats.

Is there any speed advantage? Devices compatibility?

What?

**Comment by jcready** [comment]
See https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md#protocol-differences-vs-grpc-over-http2

- `format: "text"`:
  - Payload are base64-encoded
  - `Content-type: application/grpc-web-text`
- `format: "binary"`:
  - Payload are in the binary protobuf format.
  - `Content-type: application/grpc-web+proto`

As far as I know the `format` only dictates how the client will encode the message sent to the server. The server may send back either format, but generally the server should respect the `Accept` request header. The generated client code is able to handle either format returned from the server (e.g. if you specified `Accept: application/grpc-web-text` but the server returned `Content-type: application/grpc-web+proto` the client would still decode the response just fine).

> Is there any speed advantage?

I imagine that the `binary` format would be ever so slightly faster than `text` simply because it avoids an extra encode/decode step.

**Comment by timostamm** [comment]
I believe the extra base64 encoding is necessary to read partial responses (server streaming) with `XMLHttpRequest` (but haven't fully investigated this). The fetch API we are using does not have this limitation, so if `binary` works with your backend / proxy, you get a very minor improvement in payload size and speed.

**Comment by frederikhors** [comment]
> you get a very minor improvement in payload size and speed

With binary, right?

**Comment by timostamm** [comment]
Exactly.
