### ISSUE TITLE
Plugin wide option to generate int64 as number

### ISSUE THREAD

**Issue by vicb** [timostamm/protobuf-ts#12]
There is currently no plugin wide option to set the generated int64 type to number.

See [protobufts-plugin.ts](https://github.com/timostamm/protobuf-ts/blob/3207ae7c66213bde0820c80b26d0fceac157b75d/packages/plugin/src/protobufts-plugin.ts#L81): BIG_INT and STRING are the only possible values.

Should there be a `long_type_number` option ? (and maybe as `long_type_bigint` ?)

Notes: 
- it is still possible to override this [at field level](https://github.com/timostamm/protobuf-ts/blob/adf977b9cd7a1c98e6db82a57494ff51993fd0a7/packages/runtime/src/reflection-info.ts#L339),
- I can not use BigInt because AppEngine is still on Node 12.

edit: I'm happy to work on a PR once with agree on the option names.

**Comment by timostamm** [comment]
As a quick workaround, you can:

- set the plugin option `--ts_opt long_type_string` ([see manual](https://github.com/timostamm/protobuf-ts/blob/v1.0.5/MANUAL.md#the-protoc-plugin))

- convert the string value to a [`PbLong`](https://github.com/timostamm/protobuf-ts/blob/v1.0.5/packages/runtime/src/pb-long.ts#L179) and then to a `number`:  
  `PbLong.from("123").toNumber()`

If it is an unsigned 64 bit value, use `PbULong`. 


There is no `long_type_bigint` plugin option because that is the default behaviour. But it would not hurt to have this option, if only for consistency. (Similar to `optimize_speed`, which also equals the default behaviour.)

There is no `long_type_string` option because it is not recommended to use JS number for 64 bit integers. JS number cannot represent the full range of 64 bit values. Only string and bigint representations are safe. But protobuf-ts should not be in your way if you know better. A `long_type_number` makes sense. 

Let me merge #10 before you open a PR. Should be done later today.

**Comment by timostamm** [comment]
#10 has been merged to master.

**Comment by vicb** [comment]
FYI the only `int64` I use is to transfer a datastore id which is a "safe" integer (it has been designed so it can be transmitted as a JSON number).

I'll work on the PR.

**Comment by timostamm** [comment]
Merged in PR #13. Thanks for the contribution!
