### ISSUE TITLE
Ignoring backend-only options - add a `force_exclude_options` plugin option

### ISSUE THREAD

**Issue by optiman** [timostamm/protobuf-ts#126]
Right now (`v2.0.0-alpha.27`) service and message options from `.proto` files are always generated for `ServiceType`.

It would be nice to have the ability to ignore all (or blacklist some) options for browser clients if they are used only on the backend.

These options just increase the final bundle size without ever being used or in the worst case can leak some backend implementation details, that shouldn't be visible on the frontend to everyone.

The official protoc plugin for JS is not including options in the generated files, and I think that this is a reasonable default behaviour.

**Comment by timostamm** [comment]
The official JS plugin still doesn't support the JSON representation either, as far as I know. Not sure if we should focus on that for a reference. 

It is already possible to exclude options from the generated code with a [blacklist](https://github.com/timostamm/protobuf-ts/blob/master/MANUAL.md#excluding-options-from-generated-code) using a file option: 

```proto
option (ts.exclude_options) = "*.private.*";
```

Is this an option (hah) for you?

There is no plugin option for the blacklist because I don't want to add value options, only flags. A `force_exclude_options` flag would fit well within the existing plugin options...

**Comment by optiman** [comment]
`force_exclude_options` plugin flag sounds good. 
Blacklist suggestion was just a compromise in case it was to difficult to implement exclusion of all options.

**Comment by timostamm** [comment]
Added in https://github.com/timostamm/protobuf-ts/commit/ab9d65e0f66f6957efb9d8c96f71c526b5c698b8

- "force_exclude_all_options"
  By default, custom options are included in the metadata and can be blacklisted
  with our option (ts.exclude_options). Set this option if you are certain you do not want
  to include any options at all.

**Comment by timostamm** [comment]
Released in [v2.0.4-alpha.0](https://github.com/timostamm/protobuf-ts/releases/tag/v2.0.4-alpha.0) in the `next` channel.

**Comment by timostamm** [comment]
Released in [v2.0.4](https://github.com/timostamm/protobuf-ts/releases/tag/v2.0.4).
