### ISSUE TITLE
Why I cannot get messages in real-time but only when the browser closes the pending call?

### ISSUE THREAD

**Issue by frederikhors** [timostamm/protobuf-ts#128]
I'm trying to use protobuf-ts with server streaming (https://github.com/improbable-eng/grpc-web/tree/master/go/grpcweb in Golang) but I don't get messages from server until connection is closed.

I'm using Svelte 3 like this:

```html
<script lang="ts">
	import { onDestroy, onMount } from 'svelte';

  const transport = new GrpcWebFetchTransport({ baseUrl: '/', format: 'binary' });

  const service = new EventServiceClient(transport)

	const abortController = new AbortController();

	onMount(async () => {
		const call = service.flow({}, { abort: abortController.signal });

    for await (const response of call.responses) {
			console.log('got another response!', response);
		}
	});

	onDestroy(() => abortController.abort());
</script>
```

The call in in pending state for about 2.2 min. After that I get all messages logged in console.

![image](https://user-images.githubusercontent.com/41120635/124382310-0414b280-dcc7-11eb-80ba-513c65c267d4.png)

I need them in real-time!

Where am I doing wrong?

**Comment by frederikhors** [comment]
I think this is due to: https://github.com/volatiletech/authboss/issues/325.

**Comment by frederikhors** [comment]
I will close this issue ASAP.

**Comment by timostamm** [comment]
For server streaming, the response is read in chunks. The server must send the response chunks out as soon as possible, not wait for the response to finish. 

`XMLHttpRequest` has a limitation, the only way for clients to read the response as chunks is to use a text-based format. That's why grpc-web has the text format. 

It is possible that the libraries you are using have better support for the text format. I guess the chance is rather slim though. It is more likely that the authboss middleware is just not written with streaming responses in mind.

**Comment by frederikhors** [comment]
> `XMLHttpRequest` has a limitation, the only way for clients to read the response as chunks is to use a text-based format. That's why grpc-web has the text format.

If I remove that library from my backend server `protobuf-ts` works with `binary` format too, not only `text`.

Here is the code for that middleware: https://github.com/volatiletech/authboss/blob/master/client_state.go#L123.

**Comment by timostamm** [comment]
I am sorry you got stuck with this, but I'm afraid there is nothing we can do from the protobuf-ts side. This needs some debugging of the go code to pinpoint the cause.
