### ISSUE TITLE
Automate dependencies update ?

### ISSUE THREAD

**Issue by vicb** [timostamm/protobuf-ts#14]
There are a few vulnerabilities when deps are installed:

```
$ make
npm i
audited 748 packages in 2.553s

24 packages are looking for funding
  run `npm fund` for details

found 25 vulnerabilities (4 low, 21 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

It would be nice to update dependencies automatically, i.e. using [renovate](https://www.npmjs.com/package/renovate). You can set it update to update once in a while (i.e. monthly) to avoid too much churn.

**Comment by timostamm** [comment]
The readme says `renovate` supports lerna monorepos, which sounds like a good fit. 

Do you have experience using `renovate` for a github project?

**Comment by vicb** [comment]
I have never used `renovate` on one of my repo but I see it used on a few repos.

One of the gotcha is that if you don't throttle it (i.e. once a week / a month) it could generate a lot of noise. See [skylines](https://github.com/skylines-project/skylines/commits/master).

**Comment by timostamm** [comment]
I've had a quick look at the vulnerabilities: 

```shell
npx lerna exec npm audit
```

Looks like **all** are dev dependencies. Which isn't surprising because we only have typescript as dependency, with the exception of @protobuf-ts/runtime-angular, which has some peer deps. 

Keeping dev-deps up-to-date is very low priority for me. 99% of dependencies are related to building and testing, and I would prefer to move them as seldom as possible to keep the project maintainable. 

Keeping on top of security updates is a different story. If, for example, lerna would get compromised, all packages published through lerna could become compromised.

TLDR: contributions for semi-automated security updates / notifications are welcome.

**Comment by vicb** [comment]
Not sure to get what you mean by

> TLDR: contributions for semi-automated security updates / notifications are welcome.

but 

> I would prefer to move them as seldom as possible

I could probably take a look if you clarify this point.

Thanks.

**Comment by timostamm** [comment]
> Does it means that you would upgrade the deps ONLY for security reason ?

Yes. I don't trust all those deps to be stable over updates. Have been burned by the fragile node eco-system too many times.

**Comment by vicb** [comment]
Then using [dependabot](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/about-alerts-for-vulnerable-dependencies#github-dependabot-alerts-for-vulnerable-dependencies) is probably enough ? (it should be activated for public repository by default).

**Comment by timostamm** [comment]
Possibly! Thanks for the hint. Giving it a try for some weeks...

**Comment by timostamm** [comment]
Finally got to merging the first dependabot security PRs. `npm audit` still shows warnings, though. 

To be clear, these were vulnerabilities in dev-dependencies, not in the published packages. 

Closing this and letting dependabot do its thing.
