### ISSUE TITLE
2.0.1 throwing error on install

### ISSUE THREAD

**Issue by sachaw** [timostamm/protobuf-ts#142]
Using TS `4.3.5`, upgrading from `2.0.0` to `2.0.1` throws:
```
An unexpected error occurred: "could not find a copy of typescript to link in ~/node_modules/@protobuf-ts/plugin/node_modules".
```

**Comment by timostamm** [comment]
This is a bug in yarn 1.x, see https://github.com/yarnpkg/yarn/issues/6285#issuecomment-786811393.

The following works without error in yarn 1.22.10:

```shell
yarn init -y && yarn add typescript@4.3.5 && yarn add @protobuf-ts/plugin
```

Did you find a workaround?

**Comment by sachaw** [comment]
No workaround ATM, I may be switching to pnpm though.
As I wish to use the latest TS version, I will leave the package at `2.0.0` for now,
Thanks.

**Comment by timostamm** [comment]
Thank you. Since `yarn init -y && yarn add typescript@4.3.5 && yarn add @protobuf-ts/plugin` _does_ install, I presume the error only manifests when a `node_modules` directory is present. I recommend deleting that directory before updating, or - in case that should be insufficient - deleting the lock file as well.
