### ISSUE TITLE
Repeated or Maps as Optional Properties in Typescript

### ISSUE THREAD

**Issue by glenngartner** [timostamm/protobuf-ts#149]
When I use a map or repeated property in a proto Message: 

```proto
Message Foo {
   repeated Thing things = 1;
   map<string, string> mapsOfThings = 2;
}

Message Thing {
   string key = 1;
   string value = 2;
}
```

The generated Typescript definition is: 

```typescript

export Interface Foo {
   things: Thing[];
   mapOfThings: {
      [key: string]: string;
   }
}
```

Expected result: 

maps and repeated properties are optional in the Typescript definition file. 

``` typescript
export Interface Foo {
   things?: Thing[];
   mapOfThings?: {
      [key: string]: string;
   }
}

```

Is there a way to specify this? At the moment, any maps I use are required, but I need them optional. I've read [here](https://stackoverflow.com/questions/25637687/optional-repeated-with-google-protobuf-for-java) that repeated properties are optional, by default. But, that's Java, and not sure it's the official stance.

**Comment by timostamm** [comment]
While repeated fields are optional, this refers to the presence of the field in the binary representation. 

For your .proto file, the generated Java code will be:
```java
java.util.List<X.Thing> getThingsList();
```

`getThingsList()` will never return `null`, it will always be initialized. All other language implementations I'm familiar with behave the same way. If the list is empty, the field is omitted in the binary representation. 

The generated TypeScript `interface Foo` falls in line with this behavior and types repeated fields as being always present, so that you can say `foo.things.length` instead of having to check for presence. 

Is there a chance that [PartialMessage](https://github.com/timostamm/protobuf-ts/blob/2a03386a6b01dfca26922fc6bf742629e39e0bcd/packages/runtime/src/message-type-contract.ts#L11) does what you need? `things` and `mapOfThings` are optional in `PartialMessage<Foo>`. `Foo.create()` takes a `PartialMessage<Foo>` as an argument, and returns `Foo`.

**Comment by glenngartner** [comment]
Thanks for clarifying. I'll reconsider my approach, perhaps. PartialMessage may be of use. I was a bit misled by Google's Protobuf documentation [here](https://developers.google.com/protocol-buffers/docs/overview), where they write: 


>**Required Is Forever** You should be very careful about marking fields as required. If at some point you wish to stop writing or sending a required field, it will be problematic to change the field to an optional field – old readers will consider messages without this field to be incomplete and may reject or drop them unintentionally. You should consider writing application-specific custom validation routines for your buffers instead. Some engineers at Google have come to the conclusion that using required does more harm than good; they prefer to use only optional and repeated. However, this view is not universal.

This inclined me to use optional, which makes the interface definition optional, but repeated fields are not. I'll relent, and reconsider my approach.

Thanks for clarifying. You can close the issue.
