### ISSUE TITLE
Deno build?

### ISSUE THREAD

**Issue by unicomp21** [timostamm/protobuf-ts#185]

**Comment by timostamm** [comment]
Do you know what is required to support Deno?

**Comment by unicomp21** [comment]
Does this help?

https://www.brunnerliv.io/articles/create-your-first-module-with-deno

**Comment by timostamm** [comment]
No. Have you actually tried running protobuf-ts with Deno? 

What failed specifically, and how do you propose to solve it? If Deno requires special code paths, how do we ensure they continue to function as the code base moves along?

**Comment by unicomp21** [comment]
As an aside, the nats client support for Deno, might be a good template.

https://github.com/nats-io/nats.js/search?l=Markdown&q=deno

**Comment by unicomp21** [comment]
```If Deno requires special code paths, how do we ensure they continue to function as the code base moves along?```
Tests?

**Comment by timostamm** [comment]
> Tests?

Would you like to contribute them?

**Comment by unicomp21** [comment]
Maybe, looks like the codegen will need to change for both cases.  Thinking in over.

**Comment by timostamm** [comment]
Please reopen if there are any news. For a start, we'd need to know what exactly fails to run with Deno.

**Comment by QuantumGhost** [comment]
I'm trying to use protobuf-ts with Deno.

I have tried to import `@protobuf-ts/runtime` directly in Deno with [Esh.sh](https://esm.sh/). However,  since the import statements in generated code have no `.ts` extension and [Deno not allowing import without filename extension](https://github.com/denoland/deno/issues/5368#issuecomment-628725446),  I cannot import the generated code in Deno.

[Example](https://github.com/timostamm/protobuf-ts/blob/master/packages/example-node-twirp-transport-client/service-twirp-example.client.ts#L12)

## What's expected:

The generated import statements have `.ts` extension, for example: 

```ts
import { Hat } from "./service-twirp-example.ts";
import { Size } from "./service-twirp-example.ts";
```

I think https://github.com/timostamm/protobuf-ts/pull/233 may help this.
