### ISSUE TITLE
google.protobuf.Timestamp is always generated as optional

### ISSUE THREAD

**Issue by nkovacic** [timostamm/protobuf-ts#230]
`google.protobuf.Timestamp` is always generated as optional in the TypeScript generated files.

````proto
message MediaVideo {
  // Response will use the same media_id
  string media_id = 1;
  google.protobuf.Timestamp from_timestamp = 3;
  google.protobuf.Timestamp to_timestamp = 4;
}
````
which generates:
````typescript
/**
 * @generated from protobuf message events.device_media_processor.v1.GetDeviceMediaVideoRequest
 */
export interface MediaVideo {
    /**
     * @generated from protobuf field: string media_id = 1;
     */
    mediaId: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp from_timestamp = 3;
     */
    fromTimestamp?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp to_timestamp = 4;
     */
    toTimestamp?: Timestamp;
}
````
Is this intended behavior?

**Comment by timostamm** [comment]
Hi @nkovacic, yes, this is by design. A `google.protobuf.Timestamp` is a message, and all message fields are optional. 

Version 2 of the protobuf language included a feature to make any field required. Version 3 removed this capability because you [could never remove](https://developers.google.com/protocol-buffers/docs/proto#specifying-rules) `required` without breaking old clients. 

In practice, you often run into cases where a data structure doesn't make sense without some fields. TypeScript lets us validate that quite nicely with type guards:

```ts
function isCompleteMediaVideo(arg: MediaVideo): arg is Required<MediaVideo> {
    return arg.fromTimestamp !== undefined && arg.toTimestamp !== undefined;
}

declare var mv: MediaVideo;

if (isCompleteMediaVideo(mv)) {
    mv.fromTimestamp // the compiler is aware now that the timestamps are present
}
```
