### ISSUE TITLE
Firefox stream error on reload

### ISSUE THREAD

**Issue by cortopy** [timostamm/protobuf-ts#244]
If a rpc stream is active when reloading Firefox, the stream's `onError` handler is called with this error:

```js
{ 
code: "INTERNAL",
details: null,
message: "Error in body stream",
meta: {},
methodName: "ChatQuery",
name: "RpcError",
serviceName: "ChatService" 
}
```
this doesn't happen on Chrome though.

Is there a way to avoid it?

**Comment by timostamm** [comment]
To clarify: You have an open server-stream, and reload the page in Firefox, then an error is raised?

My guess is that Firefox closes the connection (in a not very friendly way) before shutting down the JavaScript on the page. I think it might be quite difficult to distinguish that specific case from other errors in the stream. It might be helpful to look at the error produced by `fetch()` itself (we are unfortunately losing this information by wrapping in our own error).

**Comment by cortopy** [comment]
that's right, it's a chat service that gets messages as a stream. If I reload the page while the stream is connected, I get the error.

I'm using this hack

```js
if (
        error.code === 'INTERNAL' &&
        error.message === 'Error in body stream'
      ) {
        // firefox error on reload while stream is active. Do nothing
      } else {
        // report error (e.g.: Sentry)
      }
```

It works for now, but it's not ideal

**Comment by timostamm** [comment]
Looks like this was a filed as a bug on Firefox once: https://bugzilla.mozilla.org/show_bug.cgi?id=1675699

You can catch this with an interceptor. An example for a server streaming interceptor is given here: https://github.com/timostamm/protobuf-ts/blob/41faab08b42cd459ce7f70faaa0811daa9b10541/packages/runtime-rpc/src/rpc-interceptor.ts#L37-L58

You can inspect the error and omit `response.notifyError(error);` if you are sure it's the FF bug.

But this might not be sufficient, because an error in the response stream will also reject the promises for status and trailer:

https://github.com/timostamm/protobuf-ts/blob/41faab08b42cd459ce7f70faaa0811daa9b10541/packages/grpcweb-transport/src/grpc-web-transport.ts#L170-L173

You can just leave those two dangling (i.e. wrap those promises in your interceptor, and never resolve/reject them if it's the FF bug).

I'd at least check the user agent though, so that the interceptor does not swallow errors it shouldn't. It might even be an option to listen to the reload event, and only activate the interceptor then.
