### ISSUE TITLE
Declare const instead of let variables in code-generation

### ISSUE THREAD

**Issue by nvandamme** [timostamm/protobuf-ts#253]
Hi, 

The generated typescript code is using `let` only variables declarations, especialy in `internalBinaryRead` and `internalBinaryWrite` methods.

Does using the `ts.NodeFlags.Const` instead of the current flag `ts.NodeFlags.Let` can be changed without breaking the runtime generated code?

https://github.com/timostamm/protobuf-ts/blob/3e8927e93732b6c5dd970dc5f82c03e57efa7d6c/packages/plugin/src/message-type-extensions/internal-binary-read.ts#L140

**Comment by timostamm** [comment]
Hi Nicolas, 

some `let` declarations could certainly be changed for `const`. I don't see how that would break anything if done correctly.

**Comment by timostamm** [comment]
Closing this just for the sake of housekeeping. Switching to `const` will not hurt compatibility, but when the code generator was implemented, `let` actually gave a bit better performance than `const`. That's why it's used through the code base even at places where `const` would otherwise be the logical choice. Same for block-less loops. If/when the generator gets rewritten, `const` should definitely be tried again, but I'm not sure it's worth doing the change on it's own, without looking at performance again.
