### ISSUE TITLE
Best way to combine nested files

### ISSUE THREAD

**Issue by faustbrian** [timostamm/protobuf-ts#301]
Hey, was wondering what's the best/recommended way to combine a directory with nested folders and files into a single `ts` file. Currently I do something like the following with `protobufjs` for bundling:

```bash
pbjs -t static-module -w commonjs -o source/proto/nested.js proto/nested/**/*.proto && pbts -o source/proto/nested.d.ts source/proto/nested.js
```

Would there be an equivalent command for this with this lib? Something along the lines of `protoc --ts_out source/proto --proto_path proto/nested/**/*.proto` maybe.

**Comment by timostamm** [comment]
Hey Brian, can you elaborate on the purpose of `protobufjs` bundling, and what exactly it does? 

It is not clear to me what you mean with nested files. A reproducible example would be helpful.

**Comment by faustbrian** [comment]
I have a directory structure like the following:

```
tendermint
├── abci
│   └── types.proto
├── blocksync
│   └── types.proto
├── consensus
│   ├── types.proto
│   └── wal.proto
├── crypto
│   ├── keys.proto
│   └── proof.proto
├── libs
│   └── bits
│       └── types.proto
├── mempool
│   └── types.proto
├── p2p
│   ├── conn.proto
│   ├── pex.proto
│   └── types.proto
├── privval
│   ├── service.proto
│   └── types.proto
├── rpc
│   └── grpc
│       └── types.proto
├── state
│   └── types.proto
├── statesync
│   └── types.proto
├── types
│   ├── block.proto
│   ├── canonical.proto
│   ├── events.proto
│   ├── evidence.proto
│   ├── params.proto
│   ├── types.proto
│   └── validator.proto
└── version
    └── types.proto
```

Running `pbjs -t static-module -w commonjs -o source/proto/nested.js proto/nested/**/*.proto && pbts -o source/proto/nested.d.ts source/proto/nested.js` will result in the files `source/proto/nested.d.ts` and `source/proto/nested.js` being created. The `source/proto/nested.js` file contains all of the `proto` files combined instead of having a separate `js` file for each `proto` file and `source/proto/nested.d.ts` contains all of the TypeScript types.

**Comment by timostamm** [comment]
Thanks Brian, purpose and details are still a bit unclear to me, unfortunately. 

`protobuf-ts` will generate a tree similar to the input tree, not just two files. Since two messages could have the same name, you can't just `export *` in a single file. Types would have to be exposed with an interface of some kind. But that negates the advantages of ECMAScript modules, meaning that a website bundle would have to include all types, not just the used ones.

Not sure what `protobuf.js` does in this case, and whether it cares about bundle size. I'm also not sure why it offers bundling in the first place, and what problem it solves. I would expect users to simply run one of the many bundlers available on their entire frontend web application.  

If this is about distributing types, [the BSR](https://buf.build/product/bsr/) offers the best convenience at the moment. It is also an option to craft an NPM package from the generated code. I think that can be (mostly) automated, and `protobuf-ts` gives you the building blocks, but it's not an out-of-the-box solution.
