### ISSUE TITLE
`Foo$Type.create()` takes `PartialMessage<Foo>`, but could take `readonly PartialMessage<Foo>`

### ISSUE THREAD

**Issue by ryanrhee** [timostamm/protobuf-ts#462]
Can codegen be updated to include the `readonly` keyword when creating new proto messages via `.create()`?

The [dataloader](https://github.com/graphql/dataloader) api passes in the keys as a `readonly` parameter. I'm using this in a graphql resolver function, where the graphql makes a grpc call to fetch data.

The workaround is to cast the readonly field as non-readonly:

```ts
    new DataLoader(
      async (keys: readonly FooID[]) => {
        const finishedCall = await this.grpc.getFoo(
          GetFooRequest.create({
            ids: keys as FooID[],
          }),
        )
        return finishedCall.response
      }
    )
```

but it would be nice to omit the unnecessary cast.

**Comment by timostamm** [comment]
Hey Ryan, that's an interesting idea. The data passed to create() is never modified, so it would be valid to make it readonly. But it would require modifying the PartialMessage type. It is very likely that the type is used for other use cases too, so I don't think we can easily do that.

In your case, I recommend to create a copy of the array instead of a cast: `ids: [...keys]`.
