### ISSUE TITLE
Error on Vue.js component streaming call with grpcweb-transport-client

### ISSUE THREAD

**Issue by staticdev** [timostamm/protobuf-ts#472]
Hello, I started trying an example very similar to https://github.com/timostamm/protobuf-ts/tree/master/packages/example-angular-app/src/app/grpcweb-server-streaming but with Vue.js.

My proto is simply:

```
syntax = "proto3";
package extractor;

service Extract {
    rpc GetEntries (File) returns (stream Entry);
}

message File {
    string name = 1;
}

message Entry {
    string value = 1;
}
```

I have a Golang RPC server running on port 50051.

My connect code is:

```typescript
const HOST = "0.0.0.0:50051";
const TIMEOUT = Date.now() + 2000;

const extract = async () => {
  const transport = new GrpcWebFetchTransport({
    baseUrl: HOST,
    timeout: TIMEOUT,
  });
  const client = new ExtractClient(transport);

  const stream = client.getEntries({ name: "my.csv" });
  for await (let response of stream.responses) {
    console.log("got another entry! " + response);
  }
  extracted.value = true;
};
```

Problem is that when I execute it, on browser I have an error:
`404 NOT Found for POST http://localhost:5173/0.0.0.0:50051/extractor.Extract/GetEntries`
it is coupled with
`[Vue warn]: Unhandled error during execution of native event handler`
and also
`Uncaught (in promise) RpcError: Not Found`

On the other hand, if I change the `baseUrl` to `localhost:50051` instead of `0.0.0.0:50051`, I get a different error:

```
Uncaught (in promise) RpcError: NetworkError when attempting to fetch resource.
```

@timostamm any idea if there is a bug here or it is just me doing something wrong?

**Comment by timostamm** [comment]
Hey @staticdev, you say:

> I have a Golang RPC server

I assume that is https://github.com/grpc/grpc-go ?

It will serve the [gRPC protocol](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) (Content-Type application/grpc+proto), but the gRPC-web Transport actually implements the gRPC-**web** protocol ([see here](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md), and a call to formalize it [here](https://github.com/grpc/grpc/issues/30565)), which uses Content-Type application/grpc-web+proto or application/grpc-web-text+proto, and encodes trailers in the response body.

You can not speak to a gRPC server from a web browser because browsers do not expose response trailers to JS. Since you are on Go, I recommend to take at look at [Connect](https://connect.build/docs/go/getting-started).

Closing this because there is nothing we can do here.
