### ISSUE TITLE
Values being converted to undefined

### ISSUE THREAD

**Issue by Zabzx** [timostamm/protobuf-ts#496]
I'm making a request to an API and my request seems to be getting converted to undefined.

```typescript
onSubmit: async (values) => {
      console.log(values);
      try {
        chatServiceClient.createCharacter({ character: values }).then(res => {
          console.log(res);
        }).catch(err => console.log(err));
      } catch (error) {
        console.log(error);
      }
    }
```
When I console.log() the values, I get the expected data. However i get an **Error: unknown value undefined** when making a request to the server.

values:
```json
{
    "name": "test_character",
    "activePrompt": "",
    "composure": 1,
    "emotionalRulesSetId": "1",
    "generationConfigId": "1",
    "promptSetId": "10",
    "primerSetId": "6",
    "emotions": [
        {
            "pairName": "agitated_patient",
            "currentPercentage": 0
        },
        {
            "pairName": "burned_out_ambitious",
            "currentPercentage": 0
        },
        {
            "pairName": "hate_love",
            "currentPercentage": 0
        },
        {
            "pairName": "sad_happy",
            "currentPercentage": 0
        }
    ],
    "tasks": [],
    "type": ""
}
```
Error stack trace:
![image](https://user-images.githubusercontent.com/88985587/222213442-dfe8b408-4ce2-4d8d-a0bb-56b878fe73b2.png)

The issue seems to occur with the bigint.

**Comment by timostamm** [comment]
@Zabzx, if you have a proto file like this:

```proto
message M  {
  string f = 1;
}
```

This generates the interface:

```ts
interface {
  f: string;
}
```

Note that `f` is required.

If you make a call with a client that uses `M` for the request, you must give `f`.

Make sure you have TypeScript set up properly, because this should have been caught by the compiler.

Obviously you don't want to give every property all the time. If you are fine with the default value `""` for `f`, you can wrap your request object with `M.create()` before giving it to the client. This allows partial input, and sets default values for others.

This applies to your chat as well. Simply do:

```ts
chatServiceClient.createCharacter(YourMessage.create({ character: values }))
```

**Comment by Zabzx** [comment]
Thanks a lot 👍
