### ISSUE TITLE
Marking a field as [deprecated = true] should make it optional

### ISSUE THREAD

**Issue by RmStorm** [timostamm/protobuf-ts#514]
Right now deprecated fields are still required in the generated typescript unless also explicitly marked with `optional`. I think it would make quite a bit of sense for deprecated fields to become optional in the type so they can be left off.

**Comment by timostamm** [comment]
I would consider this behavior a breaking change. Let's say you have a code base that uses a field, and you introduce an alternative field, and mark the old one as deprecated. Now all code accessing the old field suddenly needs to handle `undefined`.

I totally understand that this is not ideal if you construct messages without the generated create() functions, which allow you to omit fields, because then you do have to specify fields that are marked deprecated. 

But the situation above also needs to be considered, and I think it weighs more. 

Closing this, but thank you for raising the issue!
