### ISSUE TITLE
Support for WebTransport/HTTP3

### ISSUE THREAD

**Issue by thegrumpylion** [timostamm/protobuf-ts#649]
Any plans on supporting WebTransport for the web client?

This might be relevant: https://github.com/grpc/grpc/issues/19126

**Comment by timostamm** [comment]
Hey Nikolas, I'm aware of the issue 🙂 

Unfortunately, WebTransport isn't widely available yet. Safari and Node.js do not implement it at this point. Since it's based on HTTP/3, I expect that there will be a few hurdles using it in practice. I don't quite understand how WebTransport exposes headers TBH.

So no plans to support WebTransport yet. But _if_ this really happens, I'm sure we'll have an implementation too.
