### ISSUE TITLE
[Question] Can't extends generated classes.

### ISSUE THREAD

**Issue by plaksin-a** [timostamm/protobuf-ts#82]
Can the protobuf-ts generate files with the opportunity for exporting the classes instead of the instances? I am asking because I would like to extend classes to write custom functions.

Maybe you recommend something?

**Comment by timostamm** [comment]
There is a hoisting problem with extending generated classes. Let's say you have this .proto:

```protobuf
message Foo {
   Bar bar = 1;
}

message Bar {
}
```

Now you extend Bar: 

```typescript

class MyBar extends Bar {
   greet() {
     console.log("hello world")
   }
}
```

But what happens if you deserialize this?

```typescript
let foo = Foo.deserialize(data);
foo.bar.greet() 
        ^^^^^
```

`bar` will be an instance of `Bar`, not `MyBar`. So extending generated classes only works in a very limited way.

**Comment by timostamm** [comment]
Could you give me some an example of what you want to achieve? 

Do you want to add a method to specific types, or do you want to overwrite functionality? 

Some well-known-types already have special methods:

https://github.com/timostamm/protobuf-ts/blob/7c7612dc166478779bd6ec4b54c9969541064ae8/packages/plugin/src/message-type-extensions/google-types.ts#L43-L67

I thought about exposing this functionality. So that users can add custom functions to be generated...
