### ISSUE TITLE
fromJSON type safety / being able to pass JSON objects directly into service methods

### ISSUE THREAD

**Issue by Bluskript** [timostamm/protobuf-ts#91]
Currently, `fromJSON` does not offer any type safety, resulting in a lot of manual checking of field names. It would be convenient if `fromJSON` offered more robust typing or if the service method itself was able to accept JSON representation directly.

**Comment by timostamm** [comment]
Not sure I understand. Could you elaborate with an example, please?

**Comment by Bluskript** [comment]
Actually I found there was an easy solution to my problem, and that was to pass an object to `Message.create` rather than `Message.fromJson`. It might be worth noting in the documentation that `fromJson` will accept any JSON object, and will be weakly typed. What I was referring to was how `fromJson` didn't enforce the schema of the message.

**Comment by timostamm** [comment]
Ah, thanks for the explanation. 

Yes, `Message.create()` is what you want. You can provide a partial object, omitted fields will have default values. 

See [this section](https://github.com/timostamm/protobuf-ts/blob/master/MANUAL.md#imessagetype) in the manual for a complete reference of the available functions. 

`fromJson()` accepts any JSON so that you can do a HTTP call, `JSON.parse()` and read with `Message.fromJson()`. If `fromJson()` took a strongly typed object, this would not work.  

`fromJson()` will check if the input is valid.
